FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip3 install -r requirements.txt

# copy all *.py files only
COPY *.py /app/

EXPOSE 2222

CMD ["gunicorn", "-w", "3", "-b", "0.0.0.0:2222", "api:app"]